apiVersion: v1
kind: PersistentVolume
metadata:
   name: mqsql-pv
spec:
  storageClassName: localdisk
  accessModes: 
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/mnt/data"

